import Head from "next/head";
import Image from 'next/image'
import coverImageDesktop from '../assets/Image_LandingPage_Balls_Desktop_425x832.png'

export default function Home() {
  return (
    <>
    <Head>
        <title>Yarn Help! Comming Soon</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&family=Goudy+Bookletter+1911&family=Newsreader:ital,opsz,wght@0,6..72,200;0,6..72,300;0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,200;1,6..72,300;1,6..72,400;1,6..72,500;1,6..72,600&family=Niconne&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>
    
    <main className='grid grid-cols-1 md:grid-cols-3 md:grid-rows-3 h-screen'>
      
      <Image src={ coverImageDesktop } alt="balls of yarn"  className='object-scale-down h-screen bg-contain md:object-right md:col-start-3 row-span-3'/>
      

      <div className='lg:col-span-2 lg:col-start-1 row-span-3 pl-24'>
        <h1 className="text-blackBrown font-code text-6xl">Yarn Help!</h1>
        <h2 className='text-darkPlum font-extrabold font-sans text-4xl'>Coming Soon</h2>
        <div className='lg:col-span-2 lg:col-start-1 row-span-2'>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit mollitia eaque commodi velit odio voluptatem porro necessitatibus consequatur nam, doloribus maiores officia explicabo ipsa eius quam, hic provident tempore optio.</p>
          <ul>
            <li>Item 1 link</li>
            <li>Item 2</li>
            <li>Item 3</li>
          </ul>
        </div>
     </div>
    </main>
    </>
  )
}

